[
    { "frequency": 851125000, "is_control": true, "department": "Safety", "descrption": "" },
    { "frequency": 851150000, "is_control": true, "department": "Safety", "descrption": "" },
    { "frequency": 851400000, "is_control": true, "department": "Safety", "descrption": "" },
    { "frequency": 851425000, "is_control": true, "department": "Safety", "descrption": "" },
    { "frequency": 851587500, "is_control": false, "department": "Safety", "descrption": "" },
    { "frequency": 851612500, "is_control": false, "department": "Safety", "descrption": "" },
    { "frequency": 851762500, "is_control": false, "department": "Safety", "descrption": "" },
    { "frequency": 851812500, "is_control": false, "department": "Safety", "descrption": "" },
    { "frequency": 852087500, "is_control": false, "department": "Safety", "descrption": "" },
    { "frequency": 852212500, "is_control": false, "department": "Safety", "descrption": "" },
    { "frequency": 852262500, "is_control": false, "department": "Safety", "descrption": "" },
    { "frequency": 852387500, "is_control": false, "department": "Safety", "descrption": "" },
    { "frequency": 852675000, "is_control": false, "department": "Safety", "descrption": "" },
    { "frequency": 852837500, "is_control": false, "department": "Safety", "descrption": "" },
    { "frequency": 853087500, "is_control": false, "department": "Safety", "descrption": "" },
    { "frequency": 853225000, "is_control": false, "department": "Safety", "descrption": "" },
    { "frequency": 853412500, "is_control": false, "department": "Safety", "descrption": "" },
    { "frequency": 853437500, "is_control": false, "department": "Safety", "descrption": "" },
    { "frequency": 853625000, "is_control": false, "department": "Safety", "descrption": "" },
    { "frequency": 853650000, "is_control": false, "department": "Safety", "descrption": "" },
    { "frequency": 853787500, "is_control": false, "department": "Safety", "descrption": "" },
    { "frequency": 853887500, "is_control": false, "department": "Safety", "descrption": "" },
]
